### ISSUE TITLE
Some functions like `isNotPresent` are not documented in readme

### ISSUE THREAD

**Issue by roshanrajeev** [neetozone/neeto-cist#29]
cc: @AbhayVAshokan

**Comment by AbhayVAshokan** [comment]
@ajmaln it looks like this PR was not migrated when we extracted documentation to neetoCist.

Ref: https://github.com/bigbinary/neeto-commons-frontend/pull/898/files

**Comment by AbhayVAshokan** [comment]
@shreyansh-g24 _a Migrate the above PR.
