### ISSUE TITLE
Update the format of documentation to match neeto-commons-frontend style

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-cist#32]
https://github.com/bigbinary/neeto-commons-frontend/pull/898 introduces a new format for documentation where the documentation for each function is written in a separate file. 

---

**Action Item**

- [ ] Migrate the changes in https://github.com/bigbinary/neeto-commons-frontend/pull/898.

documentation _t low-priority _t

**Comment by josephmathew900** [comment]
@adil62 _a

**Comment by josephmathew900** [comment]
@deepakjosp _a
