### ISSUE TITLE
Update the return type of `findBy` method to generic type

### ISSUE THREAD

**Issue by Prasannams97** [neetozone/neeto-cist#37]
-  Change the return type of the findBy method to generic type `<T, P>(T, P[]): P`.
<img width="882" alt="Screenshot 2024-02-19 at 2 27 31 PM" src="https://github.com/bigbinary/neeto-cist/assets/75472228/d367cfb1-4c9e-415e-8939-dc1a6c998b4d">

**Comment by Prasannams97** [comment]
@josephmathew900 _a

**Comment by josephmathew900** [comment]
@deepakjosp _a
