### ISSUE TITLE
`isPresent(false)` should not evaluate to true

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-cist#41]
![image](https://github.com/bigbinary/neeto-cist/assets/35297280/53629192-cde3-4cc7-82c8-ba87ef084276)

**Comment by josephmathew900** [comment]
<img src="https://github.com/bigbinary/neeto-cist/assets/26121158/cbf4bb22-dad8-413e-b7bf-2906046ab7c5" width="450" height="700">

**Comment by ajmaln** [comment]
IMO `isPresent` checks the presence of a value. A value is absent when it equals to `null` or `undefined` or if the object value is considered empty. So the current behavior is valid. As @josephmathew900 has mentioned, passing a condition to `isPresent` is not the right way to use it.

**Comment by AbhayVAshokan** [comment]
Understood.
