### ISSUE TITLE
Decouple the neeto packages dependencies

### ISSUE THREAD

**Issue by soorajbhaskaran** [neetozone/neeto-cist#46]
We have open-sourced this package for the public, so it is not feasible to have a neeto dependency for this package.
When I installed this package at a non-neeto project 
<img width="946" alt="Screenshot 2024-09-03 at 1 45 24 PM" src="https://github.com/user-attachments/assets/07bba7ca-3e45-4ef1-ac0f-870ad0aaf0b8">
it is instructing me to install packages like neeto-icons, neeto-molecules and neeto-ui which does not make sense for an end user since this package serves as a utility package to avoid unwanted boilerplate code. I also saw that the `antd` package was installed when I installed this package. We should decouple this repository from the unwanted dependencies so that it is straightforward.

cc// @josephmathew900, @AbhayVAshokan

**Comment by josephmathew900** [comment]
@soorajbhaskaran _a
